name: DevelopmentTest

on: [push]

jobs:
  test_compatability:  # not actually running tests, just testing dependencies are compatible
    strategy:
      matrix:
        os: [ windows-latest, macos-12, ubuntu-22.04 ]
        py: [ "3.8", "3.9" ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v2
    - name: Set up Python
      uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435  # v4.5.0
      with:
        python-version: ${{ matrix.py }}
    - name: Install Pip Dependencies from Requirements
      shell: bash
      run: pip install -r requirements.txt
      # the test here is really just to make sure the dependencies are compatible, not running any unit tests (for now)
